<a href="https://colab.research.google.com/github/hey-ABHAY/Deep_Learning/blob/main/tensors_in_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("Gpu is not available")

Gpu is not available


In [ ]:
#empty-makes a torch of given dimensions
a=torch.empty(2,3)
print(a)
print(type(a))

tensor([[1.0463e-08, 0.0000e+00, 8.7100e-12],
        [0.0000e+00, 1.4013e-45, 3.0829e-44]])
<class 'torch.Tensor'>


In [ ]:
#using zeroes
print(torch.zeros(2,3))
print(torch.ones(3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
#rand --> random ,
torch.rand(2,3)

tensor([[0.7621, 0.1719, 0.2066],
        [0.5356, 0.2112, 0.4502]])

In [ ]:
#seed function
torch.manual_seed(100) #functionality will be made same in the future
print(torch.rand(2,3))

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


In [ ]:
#using tensor-->convert to tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#arrange
print("arrange-->",torch.arange(0,10,2))

#using linspace
print("Linspace-->",torch.linspace(0,50,5))

#eye-->Identity matrix
print("Identity matrix-->",torch.eye(5))

#using ful
print("Full-->",torch.full((3,3),5))

arrange--> tensor([0, 2, 4, 6, 8])
Linspace--> tensor([ 0.0000, 12.5000, 25.0000, 37.5000, 50.0000])
Identity matrix--> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Full--> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [ ]:
x=torch.tensor([[1,2,3],[5,6,7]])
print(x.shape)

torch.Size([2, 3])


In [ ]:
torch.empty_like(x)    #we can copy the shape of the tensor
print(torch.zeros_like(x))
print(torch.ones_like(x))


tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 1, 1],
        [1, 1, 1]])



**Tensor Data Type**

In [ ]:
x.dtype

torch.int64

In [ ]:
#assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
#using .to()
x.to(torch.float64)
x.to(torch.int32)

tensor([[1, 2, 3],
        [5, 6, 7]], dtype=torch.int32)

# MAthematical operation


In [ ]:
x+2
x-2
x*3
x/3
(x*100)//3

tensor([[ 33,  66, 100],
        [166, 200, 233]])